config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  get 'players/new/:room_id', to: 'players#new', as: 'new'
  resources :players, only: [:create]

  resources :rooms, except: [:index] do
    get 'lobby'
    get 'show_main'
    get 'show_player'
    post 'question_options'
    post 'selected_answer'
    post 'player_ready'
  end

  # get 'pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :room
  has_many :round_scores

  COLOURS = ['#f893b8', '#e91e63', '#ff5722', '#ff9800', '#fbe633', '#5dd974', '#00bcd4', '#3f9efd', '#3762ff', '#a644fe'].freeze
  AVATARS = [
    'cold.png',
    'beard.png',
    'crazy.png',
    'devil.png',
    'happy-heart.png',
    'famous.png',
    'cool.png',
    'depression.png',
    'embarrassed.png',
    'emoji.png',
    'fire.png',
    'funny.png',
    'laugh.png',
    'smile.png',
    'smiley.png'
  ].freeze

  def line_chart_data
    {
      label: name,
      data: round_scores.order(:round).pluck(:score),
      borderWidth: 1
    }
  end
end

app/models/question.rb
class Question < ApplicationRecord
  def question_for(questioner_name)
    question.gsub(/%{questioner}/, "#{questioner_name}")
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :players

  def questioner
    players.find_by(questioner: true)
  end

  def answerers
    players.where(questioner: false)
  end

  def player_positions
    players.all.order(score: :desc)
  end

  def change_questioner
    players.update_all(questioner: false)
    questioner = players.where(turns_taken: current_round - 1)
    questioner.update(questioner: true)
  end

  def reset_players_answered
    players.update_all(answer: '')
  end

  def reset_players_ready_status
    players.update_all(ready: false)
  end

  def everyone_answered?
    players.where(answer: '').empty?
  end

  def everyone_ready?
    players.where(ready: false).empty?
  end

  def quiz_finished?
    questioner.nil? && rounds == current_round
  end

  def give_points
    answerers.each do |player|
      player.update(score: player.score + 1) if player.answer == questioner.answer
    end
  end

  def players_scores_for_line_graph
    JSON.generate(players.map do |player|
      player.line_chart_data
    end).html_safe
  end

  def rounds_for_line_graph
    JSON.generate(rounds.times.map do |round|
      "Round #{round + 1}"
    end).html_safe
  end
end

app/models/round_score.rb
class RoundScore < ApplicationRecord
  belongs_to :player
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
    @room = Room.find_by(room_id: params[:room_id])
  end

  def create
    @room = Room.find_by(room_id: player_params[:room_id])
    @player = Player.new(player_params.merge(room: @room))

    if @player.save
      session[:player_id] = @player.id
      players = @room.players.map{ |p| {name: p.name, colour: p.colour, avatar: view_context.image_path("profile/#{p.avatar}"), id: p.id} }
      ActionCable.server.broadcast "room_channel_#{@room_id}", {players: players}
      redirect_to room_show_player_path(room_id: @room.room_id)
    else
      render :new
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :room_id, :colour, :avatar)
  end
end

app/controllers/rooms_controller.rb
require "rqrcode"

class RoomsController < ApplicationController
  before_action :set_question, only: [:show_main]
  before_action :set_room, only: [:show_main, :show_player, :question_options, :selected_answer, :player_ready]

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.room_id = SecureRandom.hex(10)

    if @room.save
      redirect_to room_lobby_path(room_id: @room.room_id)
    else
      render :new
    end
  end

  def lobby
    @room = Room.find_by(room_id: params[:room_id])
    set_players(@room)
    @new_player_url = new_player_url
    qrcode = RQRCode::QRCode.new(@new_player_url)
    @QRCSVG = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 5,
      standalone: true,
      use_path: true
    )
  end

  def show_main
    start_quiz
  end

  def show_player
    @player = Player.find_by(id: session[:player_id])
  end

  def question_options
    @room.reset_players_answered
    correct_answer = params[:correct_answer]
    @room.questioner.update(answer: correct_answer)

    ActionCable.server.broadcast "room_channel_#{@room_id}", {
      action: 'get ready',
    }
    sleep(3)
    @room.update(question_start_time: Time.now)
    ActionCable.server.broadcast "room_channel_#{@room_id}", {
      correct_answer: @room.questioner.answer,
      question_options: random_order_options,
      questioner: @room.questioner.name,
      action: 'select answer',
    }
    return nil
  end

  def selected_answer
    player_answered = @room.players.find_by(name: params[:player_answered])
    player_answered.update(answer: params[:selected_answer])
    time_taken_to_answer = Time.now - @room.question_start_time
    player_answered.update(time_taken_to_answer: time_taken_to_answer)

    ActionCable.server.broadcast "room_channel_#{@room_id}", {
      player_answered: params[:player_answered],
      selected_answer: params[:selected_answer],
      time_taken_to_answer: time_taken_to_answer,
      colour: player_answered.colour,
      action: 'player answered'
    }
    if @room.everyone_answered?
      # TODO a method like .next_round might be better.
      @room.give_points
      @room.questioner.update(turns_taken: @room.questioner.turns_taken + 1)
      ActionCable.server.broadcast "room_channel_#{@room_id}", {
        action: 'everyone has answered',
      }
    end

    return nil
  end

  def player_ready
    player = @room.players.find_by(name: params[:player_ready])
    player.update(ready: true)

    ActionCable.server.broadcast "room_channel_#{@room_id}", {
      player_ready: params[:player_ready],
      action: 'player ready',
    }

    if @room.everyone_ready?

      start_quiz
    end

    return nil
  end

  def new_player_url
    # "#{request.protocol}#{request.remote_ip}:#{request.domain}#{request.port}/players/new/#{@room.room_id}"
    "#{request.protocol}localhost:#{request.port}/players/new/#{@room.room_id}"
  end

  private

  def random_order_options
    params[:correct_answer] + ',' + params[:incorrect_answers].split(',').filter(&:present?).map(&:strip).shuffle.join(',')
  end

  def start_quiz
    @room.change_questioner
    # TODO this won't redirect, broadcast to the room the quiz is over.
    # Then display a button on the main show page to 'Show results'
    return quiz_finished if @room.quiz_finished?

    @room.update(current_round: @room.current_round + 1) if @room.questioner.nil?

    set_question
    set_room
    ActionCable.server.broadcast "room_channel_#{@room_id}", {
      question: @question.question_for(@room.questioner.name),
      options: @question.options,
      questioner: @room.questioner.name,
      incorrect_answer_limit: @question.incorrect_answers,
      current_round: @room.current_round,
      action: 'start quiz',
    }
    @room.reset_players_ready_status
  end

  def quiz_finished
    ActionCable.server.broadcast "room_channel_#{@room_id}", {
      action: 'quiz finished',
    }
  end

  def room_params
    params.require(:room).permit(:name, :room_id, :rounds)
  end

  def set_room
    @room_id = params[:room_id]
    @room = Room.find_by(room_id: @room_id)
  end

  def set_question
    count = Question.all.count
    random_offset = rand(count)
    @question = Question.all.offset(random_offset).limit(1).first
  end

  def set_players(room)
    players = room.players.map do |p|
      {
        id: p.id,
        name: p.name,
        colour: p.colour,
        avatar: view_context.image_path("profile/#{p.avatar}")
      }
    end
    @players = JSON.generate(players)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/home.html.erb
<div class="row page-container">
  <div class="col-6 home-textContainer">
    <div>
      <h1 class="home-title">How well do you know each other?</h1>
      <p>Create a the room from the main screen you'll all share.</p>
      <%= link_to 'Create a New Room', new_room_path, class: 'btn btn-primary home-button' %>
    </div>
  </div>

  <div class="col-6 home-imgContainer">
    <%= image_tag 'illustrations/home.svg' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MultiplayerQuiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Calistoga&display=swap" rel="stylesheet">
    <%= content_for :extra_js %>
    <%= content_for :channels %>
    <%= action_cable_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <%= stylesheet_link_tag 'application' %>

  </head>
  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/players/_form.html.erb
<% content_for :channels do %>
  <%= vite_javascript_tag 'forms/player' %>
<% end %>

<div class="form-container">
  <div class="form-wrapper">
    <%= form_for [player] do |form| %>
      <% if player.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(player.errors.count, "error") %> prohibited this player model from being saved:</h2>

          <ul>
            <% player.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="row g-3">
      <div class="col-12">
        <h2 class="text-center">Your Player</h2>
        <p class="text-center">Input your player details.</p>
      </div>

      <div class="col-12">
        <%= form.label :name, :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="col-12">
        <%= form.label :colour, :colour %>
        <div class="colour-pickerContainer">
          <% Player::COLOURS.each do |colour| %>
            <label class="colour-picker" style="background-color: <%= colour %>;">
              <input type="radio" value="<%= colour %>" name="player[colour]">
            </label>
          <% end %>
        </div>
      </div>

      <div class="col-12">
        <%= form.label :avatar, :avatar %>
        <div class="avatar-pickerContainer">
          <% Player::AVATARS.each do |avatar| %>
            <label for="avatarPicker">
              <%= image_tag "profile/#{avatar}", class: "avatar-picker"%>
              <input type="radio" value="<%= avatar %>" name="player[avatar]" id="avatarPicker">
            </label>
          <% end %>
        </div>
      </div>

      <%= form.hidden_field :room_id, value: @room.room_id %>

      <div class="col-12">
        <%= form.submit "Join Quiz", class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/players/new.html.erb
<%= render partial: 'form', locals: { room: @room, player: @player } %>

app/views/rooms/_form.html.erb
<div class="form-container">
  <div class="form-wrapper">
    <%= form_for [room] do |form| %>
      <% if room.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(room.errors.count, "error") %> prohibited this room model from being saved:</h2>

          <ul>
            <% room.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="row g-3">
      <div class="col-12">
        <h2 class="text-center">Room Name</h2>
        <p class="text-center">Input the name of your room.</p>
      </div>

      <div class="col-12">
        <%= form.label :name, :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="col-12">
        <%= form.label :rounds, :rounds %>
        <%= form.number_field :rounds, min: 1, class: "form-control" %>
      </div>

      <div class="col-12">
        <%= form.submit :next, class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/rooms/_player.html.erb
<div class="playerSmall-container w-100 mb-3">
  <%= image_tag "profile/#{player.avatar}", class: 'playerSmall-icon', style: "background-color: #{player.colour};" %>
  <p><%= player.name %><span data-player="<%= player.name %>" data-player-answer="" data-time-taken=""></span></p>
</div>

app/views/rooms/_waiting.html.erb
<div id="waitingMessage" class="player-waitingContainer">
  <div aria-label="Orange and tan hamster running in a metal wheel" role="img" class="wheel-and-hamster">
	<div class="wheel"></div>
	<div class="hamster">
		<div class="hamster__body">
			<div class="hamster__head">
				<div class="hamster__ear"></div>
				<div class="hamster__eye"></div>
				<div class="hamster__nose"></div>
			</div>
			<div class="hamster__limb hamster__limb--fr"></div>
			<div class="hamster__limb hamster__limb--fl"></div>
			<div class="hamster__limb hamster__limb--br"></div>
			<div class="hamster__limb hamster__limb--bl"></div>
			<div class="hamster__tail"></div>
		</div>
	</div>
	<div class="spoke"></div>
</div>

  <h3 class="text-center mt-3"><%= @room.name %></h3>
  <p class="text-center">Waiting for the quiz to start.</p>
</div>

app/views/rooms/lobby.html.erb
<% content_for :channels do %>
  <%= vite_javascript_tag 'channels/lobby' %>
<% end %>

<% content_for :extra_js do %>
  <%= vite_javascript_tag 'vue' %>
<% end %>

<div id="roomId" data-room-id="<%= @room_id %>"></div>

<div id="app">
  <div class="row lobby-container m-0 p-0">
    <div class="col-7 qrcode-container">
      <div>
        <h4 class="text-center">Scan QR code</h4>
        <p class="text-center">Scan this QR code to join the lobby.</p>
        <div class="qrcode-wrapper"><%= raw @QRCSVG %></div>
        <p class="text-center">--------- 0r ----------</p>
        <p><%= @new_player_url %></p>
      </div>
    </div>

    <div class="col-5 lobby-wrapper">
      <h1 class="text-center">Lobby</h1>
      <h3 class="text-center lobby-roomName"><%= @room.name %></h3>
      <hr>
        <h3 class="lobby-playersTitle">Settings</h3>
        <table class="table table-striped">
          <tr>
            <td>Number of Rounds</td>
            <td><%= @room.rounds %></td>
          </tr>
        </table>
      <hr>
      <div id="users">
        <h3 class="lobby-playersTitle">Players</h3>
        <div id="userList" class="lobby-playerList">
          <player v-for="player in players" :key="player.id" :player="player"></player>
        </div>
      </div>
      <%= link_to 'Start', room_show_main_path(room_id: @room.room_id), class: 'btn btn-primary lobby-button' %>
    </div>
  </div>
</div>

<script>
  // Vite will load everything asynchonously,
  // so we need to wait for the page to load before we can access the players

  window.onload = () => {
    window.players.value = <%= @players.html_safe %>;
  }
</script>

app/views/rooms/new.html.erb
<%= render partial: 'form', locals: { room: @room } %>

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<p>Find me in app/views/rooms/show.html.erb</p>

<div id="roomId" data-room-id="<%= @room_id %>"></div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Enter your name</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_tag("/rooms/add_user/#{@room_id}", method: :post) do %>
          <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" aria-describedby="nameHelp">
          </div>

          <div class="modal-footer">
            <input type="submit" class="btn btn-primary" value="Done">
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="users">
  <h3>Users</h3>
  <ul id="userList">
    <% @room.players.each do |player| %>
      <li><%= player.name %></li>
    <% end %>
  </ul>
</div>

app/views/rooms/show_main.html.erb
<% content_for :channels do %>
  <%= vite_javascript_tag 'channels/main' %>
<% end %>

<% content_for :extra_js do %>
  <%= vite_javascript_tag 'vue' %>
<% end %>

<div id="app">
  <h1 class="text-center mt-4"><%= @room.name.titleize %></h1>
  <round-counter :current="currentRound" :total="<%= @room.rounds %>"></round-counter>

  <div id="roomId" data-room-id="<%= @room_id %>"></div>

  <div class="row">
    <div class="col-3 p-5 pe-0">
      <div id="users">
        <h2>Players</h2>
        <ul id="playerList" class="p-0">
          <% @room.player_positions.each do |player| %>
            <%= render partial: 'player', locals: { player: player } %>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="col-9 p-5">
      <%= render partial: 'shared/player_large', locals: { player: @room.questioner } %>
      <h2 id="displayQuestion" class="text-center mt-3"><%= @question.question_for(@room.questioner.name) %></h2>
      <ul class="question-options question-optionsMain" id="questionOptions"></ul>
    </div>
  </div>

  <div id="soundContainer">
    <audio id="playerAnsweredSound" src="<%= audio_path 'question_answered.wav' %>"></audio>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Quiz Finished!</h1>
        </div>
        <div class="modal-body">
          <p>Thank you for playing, continue to see your results.</p>
        </div>
        <div class="modal-footer">
          <%= link_to 'See Results', root_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>

  <div>
    <canvas id="myChart"></canvas>
  </div>
</div>

<script>
  window.onload = () => {
    window.currentRound.value = <%= @room.current_round %>;
  }
</script>

app/views/rooms/show_player.html.erb
<% content_for :channels do %>
  <%= vite_javascript_tag 'channels/player' %>
<% end %>
<div id="roomId" data-room-id="<%= @room_id %>"></div>

<%= render partial: 'waiting' %>

<%# TODO: hide the waiting container and then display everything else when the quiz starts. %>


<div class="player-topHUD">
  <small id="playersName"><%= @player.name.capitalize %></small>
  <h4 id="question" class="m-0"></h4>
  <hr>
  <p data-player-hud-info="correct" class="d-none">Select the correct answer.</p>
  <p data-player-hud-info="incorrect" class="d-none">Now select <span id="playerHUDIncorrect">0</span> / <span id="playerHUDIncorrectLimit">0</span> incorrect answers.</p>
  <p data-player-hud-info="done" class="d-none">If you're happy press 'Done'.</p>
  <p data-player-hud-info="waiting for options to be selected" class="d-none">Waiting for the options to be selected.</p>
  <p data-player-hud-info="confirm ready" class="d-none">Press ready to start the next question.</p>
  <p data-player-hud-info="ready" class="d-none">Waiting for other players to get ready.</p>
  <p data-player-hud-info="select your answer" class="d-none">Quick! Select your answer!</p>
  <p data-player-hud-info="wait for players to answer" class="d-none">Wait for players to answer.</p>
</div>

<ul class="question-options m-0 pt-2 pb-5" id="questionOptions"></ul>

<div class="player-bottomHUD">
  <%= form_tag "/rooms/#{@room_id}/question_options", method: :post, remote: true do %>
    <%= hidden_field_tag :correct_answer %>
    <%= hidden_field_tag :incorrect_answers %>
    <%= submit_tag 'Done', id: 'questionerSubmitButton', class: 'btn btn-primary d-none w-100' %>
  <% end %>

  <%= form_tag "/rooms/#{@room_id}/selected_answer", method: :post, remote: true do %>
    <%= hidden_field_tag :selected_answer %>
    <%= hidden_field_tag :player_answered, @player.name %>
    <%= submit_tag 'Answer', id: 'answererSubmitButton', class: 'btn btn-primary d-none w-100' %>
  <% end %>

  <%= form_tag "/rooms/#{@room_id}/player_ready", method: :post, remote: true do %>
    <%= hidden_field_tag :player_ready, @player.name %>
    <%= submit_tag 'Ready', id: 'playerReadyButton', class: 'btn btn-primary d-none w-100' %>
  <% end %>
</div>

app/views/shared/_player.html.erb
<div class="player-container">
  <div class="player-iconContainer">
    <%= image_tag "profile/#{player.avatar}", class: 'player-icon', style: "background-color: #{player.colour}; box-shadow: 0 0 0 10px #{player.colour}50;" %>
    <% if position %>
      <span class="player-position" style="background-color: <%= player.colour %>;"><%= position %></span>
    <% end %>
  </div>
  <p class="player-name" style="background-color: <%= player.colour %>"><%= player.name %></p>
  <p class="player-score" ><%= player.score %></p>
</div>

app/views/shared/_player_large.html.erb
<div class="player-container">
  <div class="player-iconContainer">
    <%= image_tag "profile/#{player.avatar}", class: 'player-icon', style: "background-color: #{player.colour}; box-shadow: 0 0 0 10px #{player.colour}50;" %>
    <% if defined?(position) %>
      <span class="player-position" style="background-color: <%= player.colour %>;"><%= position %></span>
    <% end %>
  </div>
  <p id="playerName" class="player-name" style="background-color: <%= player.colour %>"><%= player.name %></p>
  <% if defined?(position) %>
    <p class="player-score" ><%= player.score %></p>
  <% end %>
</div>

app/views/shared/_player_small.html.erb
<div class="playerSmall-container">
  <%= image_tag "profile/#{player.avatar}", class: 'playerSmall-icon', style: "background-color: #{player.colour};" %>
  <p><%= player.name %><span data-player="<%= player.name %>" data-player-answer="" data-time-taken=""></span></p>
</div>